### ISSUE TITLE
SimplePoParser::ParserError on valid file

### ISSUE THREAD

**Issue by wikiti** [arashm/PoParser#24]
Hello,

I've tried to parse [this PO file](https://gist.github.com/bosskovic/5930785), and it raise the following exception:

```
SimplePoParser::ParserError: SimplePoParser::ParserErrorSyntax error in lines
Syntax error in msgctxt
Syntax error in msgid
Syntax error in msgstr
Singular message without msgstr is not allowed. Line started unexpectedly with "\"on Lingoh".
Parseing result before error: '{:msgid=>"We connect developers and translators around the globe "}'
SimplePoParser filtered backtrace: SimplePoParser::ParserError
	from /home/daniel/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:181:in `msgstr'
	from /home/daniel/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:134:in `msgid'
	from /home/daniel/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:114:in `msgctxt'
	from /home/daniel/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:51:in `lines'
	from /home/daniel/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:25:in `parse'
	from /home/daniel/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/simple_po_parser-1.1.5/lib/simple_po_parser.rb:19:in `parse_message'
```

I'm guessing it's because it doesn't support this multiline properties with this syntax:

```
msgid "This line"
" continues on this one."
```

**Comment by dfherr** [comment]
Yes, multiline messages are expected to start with an empty line like this:

```
msgid ""
"Text here"
"and here"
```

Apparently this isn't a strict syntax error according to https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html but just always used as compliance to the msgformat implementation in Solaris. From what I remember msgformat and msgmerge tools on Ubuntu also automatically change to thix syntax.

So I would suggest you to comply with the standard syntax, but we would accept a pull request to support this alternate syntax.

**Comment by dfherr** [comment]
The changes would have to be made to the parser: https://github.com/experteer/simple_po_parser

**Comment by dfherr** [comment]
Thanks to @mgruner Upgrading to v1.1.6 of simple_po_parser will support content on the first line of multiline strings.
