### ISSUE TITLE
Incorrectly labeled header

### ISSUE THREAD

**Issue by mtimoustafa** [arashm/PoParser#30]
The [`report_to` header](https://github.com/arashm/PoParser/blob/master/lib/poparser/constants.rb#L28) should be `'Report-Msgid-Bugs-To'`, looks like a typo. Thanks!

**Comment by arashm** [comment]
Thanks for the report. Just pushed a new version with the correct attribute name.

**Comment by arashm** [comment]
Actually made a mistake. Will release a new version.

**Comment by arashm** [comment]
Released and pushed 3.2.8 version.
