### ISSUE TITLE
obsolete entries

### ISSUE THREAD

**Issue by dfherr** [arashm/PoParser#5]
Does your gem handle obsolete entries? https://www.gnu.org/software/gettext/manual/html_node/Obsolete-Entries.html They are part of the specification, but I couldn't find anything about them in your code.

I pretty much need exactly what your parser does, but with support for obsolete messages.

**Comment by dfherr** [comment]
ok, i simply overread it and found it the moment after i opened the issue.... my bad. seems like you named them cached entries

**Comment by dfherr** [comment]
reopened as cached could be renamed to obsolete to go along with the official documentation.

these entries are actually not only kept for later use but identify translations that became obsolete after a message merge (i.e. messages that were no longer found by xgettext and are no longer in the pot but still in the previously translated po)

**Comment by arashm** [comment]
Thanks for the report. I just released `1.0.3` and added `Entry#obsolete?` and `Po.obsolete` methods.

**Comment by dfherr** [comment]
thanks, that was fast ;)
