### ISSUE TITLE
does not parse merged headers and removes #fuzzy marker

### ISSUE THREAD

**Issue by dfherr** [arashm/PoParser#6]
the parser does not handle merged header entries (e.g. from msgmerge or msgcat utilities) and removes the #, fuzzy marker of the header.

example file:
```
# Test po
# Copyright (c) 2014 Experteer GmbH
#
#, fuzzy
msgid ""
msgstr ""
"#-#-#-#-#  test1.po (PACKAGE VERSION)  #-#-#-#-#\n"
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-11-09 17:12+0100\n"
"PO-Revision-Date: 2007-07-18 09:12+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"#-#-#-#-#  test2.po (PACKAGE VERSION)  #-#-#-#-#\n"
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2016-11-09 17:12+0100\n"
"PO-Revision-Date: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"

# excelrow: 9
#: ../../app/b_logic/a/b/xyz.rb:68
#: ../../app/b_logic/a/e/art.rb:80
msgctxt "Signup"
msgid "Registrierung erfolgreich!"
msgstr "Registration succesful!"
```

expected output (e.g. simply running "msgcat test.po"):

```
# Test po
# Copyright (c) 2014 Experteer GmbH
#
#, fuzzy
msgid ""
msgstr ""
"#-#-#-#-#  test1.po (PACKAGE VERSION)  #-#-#-#-#\n"
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-11-09 17:12+0100\n"
"PO-Revision-Date: 2007-07-18 09:12+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"#-#-#-#-#  test2.po (PACKAGE VERSION)  #-#-#-#-#\n"
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2016-11-09 17:12+0100\n"
"PO-Revision-Date: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
```

actual output of `puts po.header`:

```
# Test po
# Copyright (c) 2014 Experteer GmbH
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-11-09 17:12+0100\n"
"PO-Revision-Date: \n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;#-#-#-#-#  test1.po (PACKAGE VERSION)  #-#-#-#-#\n"
```

**Comment by dfherr** [comment]
fyi: this seems to be a to_s issue too. the hash representation looks okay

**Comment by arashm** [comment]
I'm not sure what is the correct way of fixing this. Since PoParser provides getters and setters for header options, now that we have two of the same keys, which one should be considered as the one that should be edited? A fuzzy header doesn't really makes sense. How should PoParser behave with it?

I checked the file with [Poedit](http://poedit.net/), it doesn't seem to be able to parse merge headers like this, and it's result is almost identical to PoParser.

Then I checked [Gtranslator](https://wiki.gnome.org/Apps/Gtranslator), it also removes the `fuzzy` string but keeps all the merged options. When saving and updating headers it only changes the first occurrence.

There doesn't seem to be an standard here that everyone could follow. What is your expectation?

**Comment by dfherr** [comment]
first about the fuzzy marker:
the fuzzy marker in the header indicates that the translator needs to check the header information for correctness. E.g. updating language-team, last-translator and so on. It's therefore basically the same as a fuzzy marker on a translation and should be handled by the parser. Removing it is imho incorrect.

about the merged header:
i'm actually also not sure how to handle this. It's also not that important for me as I'm parsing the single files and only msgcat'ing them before msgfmt'ing them to one big MO-catalog. But i reported it as it's a PO-standard-tool output.

What I would expect is that the parser would not alter these headers on "parse"->"to_s" and simply keep them as is. Perhabs a "header-array" and an "merged_header?" indicator would be a solution, when there are merged headers. The performance impact should be minor as it's only for the first entry and backwards compatibility for all single-header files would be given too. Then you can use setters and getters on header[0], header[1] and so on.

Btw there can also be merged translation entrys. They happen when you msgcat two files with the same message (msgid+msgctxt) but different translations or comments. I checked that the parser handles these merged comments, but if i recall correctly he also fails on the then "fuzzy-merged" translations (they do get a fuzzy flag in the process). But I didn't report these as they are a fucked-up scenario anyways (translators screwed up if they translate the same text differently or developers failed if they didn't provide a msgcontext if identical text needs to be translated differently) and they show up as fuzzy translations after two files without any fuzzies where merged.

**Comment by arashm** [comment]
Fixed by @dfherr on https://github.com/arashm/PoParser/commit/b6502ab31c3aefa94ce4c8249198cb7a346cdf24
